In [ ]:
import pandas as pd
data = pd.read_csv( "/content/data.csv", encoding='unicode_escape' )
data.head()

# courtesy of https://towardsdatascience.com/named-entity-recognition-ner-using-keras-bidirectional-lstm-28cd3f301f54

Sentence #      Word POS Tag
0  Sentence: 1        My   .   O
1          NaN  sobriety   .   O
2          NaN      date   .   O
3          NaN        is   .   O
4          NaN  2202022,   .   O

In [ ]:
from itertools import chain
def get_dict_map(data, token_or_tag):
    tok2idx = {}
    idx2tok = {}
    
    if token_or_tag == 'token':
        vocab = list(set(data['Word'].to_list()))
    else:
        vocab = list(set(data['Tag'].to_list()))
    
    idx2tok = {idx:tok for  idx, tok in enumerate(vocab)}
    tok2idx = {tok:idx for  idx, tok in enumerate(vocab)}
    return tok2idx, idx2tok


token2idx, idx2token = get_dict_map(data, 'token')
tag2idx, idx2tag = get_dict_map(data, 'tag')

In [ ]:
data['Word_idx'] = data['Word'].map(token2idx)
data['Tag_idx'] = data['Tag'].map(tag2idx)
data.head()

Sentence #      Word POS Tag  Word_idx  Tag_idx
0  Sentence: 1        My   .   O      1779        2
1          NaN  sobriety   .   O       179        2
2          NaN      date   .   O      1417        2
3          NaN        is   .   O      2700        2
4          NaN  2202022,   .   O      1832        2

In [ ]:
# Fill na
data_fillna = data.fillna(method='ffill', axis=0)
# Groupby and collect columns
data_group = data_fillna.groupby(
['Sentence #'],as_index=False
)['Word', 'POS', 'Tag', 'Word_idx', 'Tag_idx'].agg(lambda x: list(x))
# Visualise data
data_group.head(20)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  


Sentence #                                               Word  \
0     Sentence: 1  [My, sobriety, date, is, 2202022,, and, today,...   
1    Sentence: 10  [Maybe, you're, like, me, and, feel, you, need...   
2   Sentence: 100               [The, thought, makes, me, cringe, .]   
3   Sentence: 101  [I, do, not, want, to, experience, what, I, di...   
4   Sentence: 102  [Today's, gonna, be, rough,, but, as, I, alway...   
5   Sentence: 103  [IWNDWYT, I, have, been, sober, for, just, ove...   
6   Sentence: 104  [For, some, reason, this, time, feels, differe...   
7   Sentence: 105  [I, have, a, friend, who, has, been, on, and, ...   
8   Sentence: 106                    [She, called, me, yesterday, .]   
9   Sentence: 107  [The, thing, that, struck, me, most, was, the,...   
10  Sentence: 108  [The, kind, that, I, used, to, tell,, the, kin...   
11  Sentence: 109  [Before,, I, would, have, played, along, with,...   
12   Sentence: 11  [It, doesn't, matter, if, you're, still, hung,...   
13  Sentence: 110  [Like, I, said,, though,, this, time, for, me,...   
14  Sentence: 111  [It, was, harrowing, really,, to, realise, how...   
15  Sentence: 112   [Lying, to, others, and, lying, to, yourself, .]   
16  Sentence: 113  [Stp, one, for, recovery:, stop, lying, and, f...   
17  Sentence: 114  [Feel, great, but, sleep, is, still, not, wher...   
18  Sentence: 115  [Maybe, a, few, more, days, and, that, will, b...   
19  Sentence: 116  [IWNDWYT, *We, may, be, anonymous, strangers, ...   

                                                  POS  \
0                   [., ., ., ., ., ., ., ., ., ., .]   
1   [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
2                                  [., ., ., ., ., .]   
3          [., ., ., ., ., ., ., ., ., ., ., ., ., .]   
4   [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
5                   [., ., ., ., ., ., ., ., ., ., .]   
6   [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
7   [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
8                                     [., ., ., ., .]   
9   [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
10  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
11  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
12  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
13  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
14  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   
15                           [., ., ., ., ., ., ., .]   
16                  [., ., ., ., ., ., ., ., ., ., .]   
17      [., ., ., ., ., ., ., ., ., ., ., ., ., ., .]   
18            [., ., ., ., ., ., ., ., ., ., ., ., .]   
19  [., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ...   

                                                  Tag  \
0                   [O, O, O, O, O, O, O, O, O, O, O]   
1   [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
2                                  [O, O, O, O, O, O]   
3          [O, O, O, O, O, O, O, O, O, O, O, O, O, O]   
4   [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
5                   [O, O, O, O, O, O, O, O, O, O, O]   
6   [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
7   [O, O, O, Person, O, O, O, O, O, O, O, O, O, O...   
8                                     [O, O, O, O, O]   
9   [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
10  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
11  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
12  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
13  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
14  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
15                           [O, O, O, O, O, O, O, O]   
16                  [O, O, O, O, O, O, O, O, O, O, O]   
17      [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]   
18            [O, O, O, O, O, O, O, O, O, O, O, O, O]   
19  [O, O, O, O, O, Person, O, O, O, O, O, O, O, O...   

                                             Word_idx  \
0   [1779, 179, 1417, 2700, 1832, 1526, 7

In [ ]:
from sklearn.model_selection import train_test_split
# from keras.preprocessing.sequence import pad_sequences
from keras_preprocessing.sequence import pad_sequences
# !pip install keras-utils
from tensorflow.keras.utils import to_categorical

In [ ]:
def get_pad_train_test_val(data_group, data):

    #get max token and tag length
    n_token = len(list(set(data['Word'].to_list())))
    n_tag = len(list(set(data['Tag'].to_list())))

    #Pad tokens (X var)    
    tokens = data_group['Word_idx'].tolist()
    maxlen = max([len(s) for s in tokens])
    pad_tokens = pad_sequences(tokens, maxlen=maxlen, dtype='int32', padding='post', value= n_token - 1)

    #Pad Tags (y var) and convert it into one hot encoding
    tags = data_group['Tag_idx'].tolist()
    pad_tags = pad_sequences(tags, maxlen=maxlen, dtype='int32', padding='post', value= tag2idx["O"])
    n_tags = len(tag2idx)
    pad_tags = [to_categorical(i, num_classes=n_tags) for i in pad_tags]
    
    #Split train, test and validation set
    tokens_, test_tokens, tags_, test_tags = train_test_split(pad_tokens, pad_tags, test_size=0.1, train_size=0.9, random_state=2020)
    train_tokens, val_tokens, train_tags, val_tags = train_test_split(tokens_,tags_,test_size = 0.25,train_size =0.75, random_state=2020)

    print(
        'train_tokens length:', len(train_tokens),
        '\ntrain_tokens length:', len(train_tokens),
        '\ntest_tokens length:', len(test_tokens),
        '\ntest_tags:', len(test_tags),
        '\nval_tokens:', len(val_tokens),
        '\nval_tags:', len(val_tags),
    )
    
    return train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags

train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = get_pad_train_test_val(data_group, data)

train_tokens length: 672 
train_tokens length: 672 
test_tokens length: 100 
test_tags: 100 
val_tokens: 225 
val_tags: 225


In [ ]:
def get_trim_train_test_val(data_group, data):

    #get max token and tag length
    n_token = len(list(set(data['Word'].to_list())))
    n_tag = len(list(set(data['Tag'].to_list())))

    #Pad tokens (X var)    
    tokens = data_group['Word_idx'].tolist()
    maxlen = max([len(s) for s in tokens])
    pad_tokens = pad_sequences(tokens, maxlen=20, dtype='int32', truncating='post', value= n_token - 1)

    #Pad Tags (y var) and convert it into one hot encoding
    tags = data_group['Tag_idx'].tolist()
    pad_tags = pad_sequences(tags, maxlen=20, dtype='int32', truncating='post', value= tag2idx["O"])
    n_tags = len(tag2idx)
    pad_tags = [to_categorical(i, num_classes=n_tags) for i in pad_tags]
    
    #Split train, test and validation set
    tokens_, test_tokens, tags_, test_tags = train_test_split(pad_tokens, pad_tags, test_size=0.1, train_size=0.9, random_state=2020)
    train_tokens, val_tokens, train_tags, val_tags = train_test_split(tokens_,tags_,test_size = 0.25,train_size =0.75, random_state=2020)

    print(
        'train_tokens length:', len(train_tokens),
        '\ntrain_tokens length:', len(train_tokens),
        '\ntest_tokens length:', len(test_tokens),
        '\ntest_tags:', len(test_tags),
        '\nval_tokens:', len(val_tokens),
        '\nval_tags:', len(val_tags),
    )
    
    return train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags

train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = get_trim_train_test_val(data_group, data)

train_tokens length: 672 
train_tokens length: 672 
test_tokens length: 100 
test_tags: 100 
val_tokens: 225 
val_tags: 225


In [ ]:
def get_nopad_train_test_val(data_group, data):

    #get max token and tag length
    n_token = len(list(set(data['Word'].to_list())))
    n_tag = len(list(set(data['Tag'].to_list())))

    #Pad tokens (X var)    
    tokens = data_group['Word_idx'].tolist()
    maxlen = max([len(s) for s in tokens])
    pad_tokens = tokens

    #Pad Tags (y var) and convert it into one hot encoding
    tags = data_group['Tag_idx'].tolist()
    pad_tags = tags
    n_tags = len(tag2idx)
    pad_tags = [to_categorical(i, num_classes=n_tags) for i in pad_tags]
    
    #Split train, test and validation set
    tokens_, test_tokens, tags_, test_tags = train_test_split(pad_tokens, pad_tags, test_size=0.1, train_size=0.9, random_state=2020)
    train_tokens, val_tokens, train_tags, val_tags = train_test_split(tokens_,tags_,test_size = 0.25,train_size =0.75, random_state=2020)

    print(
        'train_tokens length:', len(train_tokens),
        '\ntrain_tokens length:', len(train_tokens),
        '\ntest_tokens length:', len(test_tokens),
        '\ntest_tags:', len(test_tags),
        '\nval_tokens:', len(val_tokens),
        '\nval_tags:', len(val_tags),
    )
    
    return train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags

train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = get_nopad_train_test_val(data_group, data)

train_tokens length: 672 
train_tokens length: 672 
test_tokens length: 100 
test_tags: 100 
val_tokens: 225 
val_tags: 225


In [ ]:
import numpy as np
import tensorflow
from tensorflow.keras import Sequential, Model, Input
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from tensorflow.keras.utils import plot_model

In [ ]:
from numpy.random import seed
seed(1)
tensorflow.random.set_seed(2)

In [ ]:
input_dim = len(list(set(data['Word'].to_list())))+1
output_dim = 64
# input_length = max([len(s) for s in data_group['Word_idx'].tolist()])
input_length = 20
n_tags = len(tag2idx)
print('input_dim: ', input_dim, '\noutput_dim: ', output_dim, '\ninput_length: ', input_length, '\nn_tags: ', n_tags)

input_dim:  3118 
output_dim:  64 
input_length:  20 
n_tags:  3


In [ ]:
def get_bilstm_lstm_model():
    model = Sequential()

    # Add Embedding layer
    model.add(Embedding(input_dim=input_dim, output_dim=output_dim))

    # Add bidirectional LSTM
    model.add(Bidirectional(LSTM(units=output_dim, return_sequences=True, dropout=0.2, recurrent_dropout=0.2), merge_mode = 'concat'))

    # Add LSTM
    model.add(LSTM(units=output_dim, return_sequences=True, dropout=0.5, recurrent_dropout=0.5))

    # Add timeDistributed Layer
    model.add(TimeDistributed(Dense(n_tags, activation="relu")))

    #Optimiser 
    # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)

    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    
    return model

In [ ]:
def get_unameliorated_bilstm_lstm_model():
    model = Sequential()

    # Add Embedding layer
    model.add(Embedding(input_dim=input_dim, output_dim=output_dim, input_length=input_length))

    # Add bidirectional LSTM
    model.add(Bidirectional(LSTM(units=output_dim, return_sequences=True, dropout=0.2, recurrent_dropout=0.2), merge_mode = 'concat'))

    # Add LSTM
    model.add(LSTM(units=output_dim, return_sequences=True, dropout=0.5, recurrent_dropout=0.5))

    # Add timeDistributed Layer
    # model.add(TimeDistributed(Dense(n_tags, activation="relu")))

    #Optimiser 
    # adam = k.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)

    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    
    return model

In [ ]:
def train_model(X, y, model):
    loss = list()
    for i in range(5):
        # fit model for one epoch on this sequence
        hist = model.fit(X, y, batch_size=1, verbose=1, epochs=1, validation_split=0.2)
        loss.append(hist.history['loss'][0])
    return loss

In [ ]:
results = pd.DataFrame()
model_bilstm_lstm = get_bilstm_lstm_model()
plot_model(model_bilstm_lstm)
results['with_add_lstm'] = train_model( train_tokens, np.array(train_tags), model_bilstm_lstm)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 64)          199552    
                                                                 
 bidirectional_4 (Bidirectio  (None, None, 128)        66048     
 nal)                                                            
                                                                 
 lstm_9 (LSTM)               (None, None, 64)          49408     
                                                                 
 time_distributed_4 (TimeDis  (None, None, 3)          195       
 tributed)                                                       
                                                                 
Total params: 315,203
Trainable params: 315,203
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  after removing the cwd from sys.path.


ValueError: ignored

In [ ]:
results.head()

with_add_lstm
0       0.103203
1       0.079540
2       0.079546
3       0.079540
4       0.079540

In [ ]:
results1 = pd.DataFrame()
unameliorated_model_bilstm_lstm = get_unameliorated_bilstm_lstm_model()
plot_model(unameliorated_model_bilstm_lstm)
results1['with_add_lstm'] = train_model(train_tokens, np.array(train_tags), unameliorated_model_bilstm_lstm)

In [ ]:
sentence1 = np.array( ["Friends", "and", "family", "at", "the", "bar"] )
tokens1 = list( map( lambda x: token2idx[x], sentence1 ) )
testicle_uno = np.concatenate( [np.array( tokens1 ), np.array( [3117 for i in range( 14 )] )], axis=0 )
predicciones = model_bilstm_lstm( np.array(  [testicle_uno for i in range(10)] ) )

In [ ]:
idx2token[2839]

'alone'

In [ ]:
predicciones[0][0]

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , 0.02500861, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ], dtype=float32)>

In [ ]:
answers_uno = np.concatenate( [np.array( [10, 3, 4, 3, 3, 0] ), np.array( [3 for i in range( 14 )] )], axis=0 )
answers_uno = np.array( [10, 3, 4, 3, 3, 0] )
target_uno = np.eye( 168 )[answers_uno]
target_uno = target_uno[:, :12]
# model_bilstm_lstm.evaluate( np.array( [testicle_uno for i in range(25)] ), np.array( [target_uno for i in range(25)] ), batch_size=25 )
model_bilstm_lstm.evaluate( np.array( [testicle_uno[:6]] ), np.array( [target_uno] ) )

1/1 [==============================] - 1s 1s/step - loss: 8.0590 - accuracy: 0.5000


[8.05904769897461, 0.5]

In [ ]:
target_uno

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
idx2tag

{0: 'Location:bar',
 1: 'Person:stranger',
 2: 'Person:alone',
 3: 'O',
 4: 'Person:family',
 5: 'Location:work',
 6: 'Person:partner',
 7: 'Location:school',
 8: 'Person:one_friend',
 9: 'Location:home',
 10: 'Person:multiple_friends',
 11: 'Location:supermarket'}

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])